name: Auto Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install hub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y hub

      - name: Create Pull Request
        run: |
          # Create the pull request
          hub pull-request -b main -h release -m "Merge main into release"
