name: Manual PR Trigger

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release branch name'
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install create-pull-request
        run: npm install -g create-pull-request

      - name: Create Pull Request
        run: |
          # Set the release branch name
          RELEASE_BRANCH=$RELEASE_BRANCH_NAME

          # Create the pull request
          create-pull-request --base main --head $RELEASE_BRANCH --title "Merge main into $RELEASE_BRANCH"

        env:
          RELEASE_BRANCH_NAME: ${{ github.event.inputs.release_branch }}
