name: Auto Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          # Create the pull request
          gh pr create --base main --head release --title "Merge main into release"
